import type { Metadata, Viewport } from 'next'
import type { ReactNode } from 'react'

import { Analytics } from '@vercel/analytics/next'
import { SpeedInsights } from '@vercel/speed-insights/next'

import { fontVariables } from '@/app/fonts'
import '@/app/globals.css'
import { Frame } from '@/components/layout/frame'
import { SiteFooter } from '@/components/layout/site-footer'
import { SiteHeader } from '@/components/layout/site-header'
import { SkipLink } from '@/components/layout/skip-link'
import { MotionProvider } from '@/components/motion/motion-provider'
import { site } from '@/content/site'
import { staticColors } from '@/lib/static-colors'

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — Web development agency`,
    template: `%s — ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    siteName: site.name,
    url: site.url,
    title: `${site.name} — Web development agency`,
    description: site.description,
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: `${site.name} — Web development agency`,
    description: site.description,
  },
  robots: { index: true, follow: true },
  // Static monochrome mark from /public; the 180px apple-icon is generated by
  // src/app/apple-icon.tsx.
  icons: { icon: [{ url: '/icon.svg', type: 'image/svg+xml' }] },
}

export const viewport: Viewport = {
  themeColor: staticColors.void,
  // No user-scalable=no — the page must zoom to 200% (§13).
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({
  children,
  modal,
}: {
  children: ReactNode
  modal: ReactNode
}) {
  return (
    <html lang={site.locale} className={fontVariables}>
      <body>
        <SkipLink />
        <Frame>
          <SiteHeader />
          <main id="main">{children}</main>
          <SiteFooter />
        </Frame>
        {modal}
        <MotionProvider />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  )
}
